import type { Metadata } from "next";
import { Raleway } from "next/font/google";

import "./globals.css";
import Header from "./../components/Header";

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.className} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
